# -*- coding: utf-8 -*-
"""PDS_ASSIGNMENT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157tUfR2yWWWNDfWrh1r0rDVycg4-CAlG
"""

cleaned_dataset_filename = 'cleaned_used_cars_dataset.csv'
data.to_csv(cleaned_dataset_filename, index=False)

!pip install matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned data
data_encoded = pd.read_csv('/content/cleaned_used_cars_dataset.csv')

# Histogram of Price
plt.figure(figsize=(10, 6))
sns.histplot(data_encoded['Price'], bins=30, kde=True)
plt.title('Distribution of Used Car Prices')
plt.xlabel('Price (Lakhs)')
plt.ylabel('Frequency')
plt.show()




# Scatter plot for Engine vs Price
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Engine', y='Price', data=data_encoded)
plt.title('Engine Displacement vs Price')
plt.xlabel('Engine Displacement (CC)')
plt.ylabel('Price (Lakhs)')
plt.show()

# Scatter plot for Mileage vs Price
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Mileage', y='Price', data=data_encoded)
plt.title('Mileage vs Price')
plt.xlabel('Mileage (kmpl)')
plt.ylabel('Price (Lakhs)')
plt.show()




# Pair plot for numerical features
sns.pairplot(data_encoded[['Price', 'Mileage', 'Engine', 'Power']], diag_kind='kde')
plt.suptitle('Pair Plot of Numerical Features', y=1.02)
plt.show()